regCenter:
  serverList: "local-dev:2181"
  namespace: "elastic-job-demo"

simpleJob:
  cron: "*/15 * * * * ?"
  shardingTotalCount: 1
  shardingItemParameters: ""

dataflowJob:
  cron: "*/15 * * * * ?"
  shardingTotalCount: 4
  shardingItemParameters: ""

spring:
  datasource:
    url: jdbc:mysql://local-dev:3306/job_demo?useSSL=false
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#spring.datasource.url= jdbc:mysql://local-dev:3306/job_demo?useSSL=false
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

pagehelper:
  helperDialect: mysql
  reasonable: true