logging:
    config: classpath:config/logback-spring.xml


mybatis:
    configuration:
        local-cache-scope: session
        map-underscore-to-camel-case: true
        use-generated-keys: true


pagehelper:
    reasonable: true
    support-methods-arguments: true


spring:
    datasource:
        data: classpath:db/data.sql
        schema: classpath:db/schema.sql
        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: org.h2.Driver
        druid:
            url: jdbc:mysql://local-dev:3306/druid_demo?useUnicode=true&characterEncoding=utf8
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            username: root
            password: root
            filter:
                slf4j:
                    enabled: true
                    connection-log-enabled: false
                    statement-log-error-enabled: true
                    statement-executable-sql-log-enable: true
                    statement-execute-after-log-enabled: true
                    statement-execute-batch-after-log-enabled: true
                    statement-execute-query-after-log-enabled: true
                    statement-execute-update-after-log-enabled: true
                    statement-create-after-log-enabled: false
                    statement-parameter-set-log-enabled: false
                    statement-prepare-after-log-enabled: false
                    statement-prepare-call-after-log-enabled: false
                    statement-sql-pretty-format: false
                    statement-parameter-clear-log-enable: false
                    statement-sql-format-option:
                        parameterized: false
                        prettyFormat: false
                        uppCase: true

                stat:
                    db-type: mysql
                    log-slow-sql: true
                    merge-sql: true
                    slow-sql-millis: 2000

            filters: stat,mergeStat,wall,slf4j
            initialSize: 5
            log-different-thread: true
            maxActive: 20
            maxPoolPreparedStatementPerConnectionSize: 20
            maxWait: 60000
            minEvictableIdleTimeMillis: 300000
            minIdle: 5
            poolPreparedStatements: true
            testOnBorrow: false
            testOnReturn: false
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 60000
            useGlobalDataSourceStat: true
            validationQuery: SELECT 1

    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: true
                web-allow-others: true
    jackson:
        property-naming-strategy: SNAKE_CASE
