spring:
  boot:
    admin:
      client:
        url: http://localhost:2222
#  jackson:
#    property-naming-strategy: SNAKE_CASE
  application:
    name: spring-boot-app-1
    admin:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:

        include: "*"
    web:
      exposure:
        include: "*"
  # METRICS
  metrics:
    export:
      atlas:
        enabled: true
        step: 1s
    binders:
      jvm:
        enabled: true

# undertow web 容器配置
server:
  undertow:
    io-threads: 1
    worker-threads: 8


# 日志格式配置
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [${spring.application.name:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

